version: '2'

services:
  webgrabplus:

    image: linuxserver/webgrabplus
    container_name: webgrabplus
    privileged: true
    restart: always

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./data:/data

    environment:
      - TZ=America/Los_Angeles
      - PGID=0
      - PUID=0

    # See: https://docs.docker.com/engine/reference/run/#cpu-share-constraint
    cpu_shares: 512
